local manager = require("utils.manager")

manager.lock()
require("plugins.2048")(manager)
require("plugins.Comment")(manager)
require("plugins.blamer")(manager)
require("plugins.bufferline")(manager)
require("plugins.bufman")(manager)
require("plugins.capture")(manager)
require("plugins.cmdline-hl")(manager)
require("plugins.dashboard")(manager)
require("plugins.ddc.ddc")(manager)
require("plugins.ddc.ddc-fuzzy")(manager)
require("plugins.ddc.ddc-filter-matcher_head")(manager)
require("plugins.ddc.ddc-filter-sorter_rank")(manager)
require("plugins.ddc.ddc-path")(manager)
require("plugins.ddc.ddc-source-buffer")(manager)
require("plugins.ddc.ddc-source-cmdline")(manager)
require("plugins.ddc.ddc-source-file")(manager)
require("plugins.ddc.ddc-source-lsp")(manager)
require("plugins.ddc.ddc-ui-native")(manager)
require("plugins.ddu.ddu")(manager)
require("plugins.ddu.ddu-filter-converter_devicon")(manager)
require("plugins.ddu.ddu-filter-converter_hl_dir")(manager)
require("plugins.ddu.ddu-filter-matcher_substring")(manager)
require("plugins.ddu.ddu-kind-file")(manager)
require("plugins.ddu.ddu-source-action")(manager)
require("plugins.ddu.ddu-source-buffer")(manager)
require("plugins.ddu.ddu-source-command_history")(manager)
require("plugins.ddu.ddu-source-file_rec")(manager)
require("plugins.ddu.ddu-source-git_status")(manager)
require("plugins.ddu.ddu-source-keymap")(manager)
require("plugins.ddu.ddu-source-line_dir")(manager)
require("plugins.ddu.ddu-source-lsp")(manager)
require("plugins.ddu.ddu-ui-ff")(manager)
require("plugins.denippet")(manager)
require("plugins.deps.denops")(manager)
require("plugins.deps.nui")(manager)
require("plugins.deps.nvim-web-devicons")(manager)
require("plugins.deps.plenary")(manager)
require("plugins.dial")(manager)
require("plugins.dropbar")(manager)
require("plugins.fidget")(manager)
require("plugins.f-string-toggle")(manager)
require("plugins.friendly-snippets")(manager)
require("plugins.gitsigns")(manager)
require("plugins.history-ignore")(manager)
require("plugins.hlargs")(manager)
require("plugins.hlchunk")(manager)
require("plugins.hop")(manager)
require("plugins.indent-blankline")(manager)
require("plugins.lazygit")(manager)
require("plugins.lsp.lazydev")(manager)
require("plugins.lsp.mason")(manager)
require("plugins.lsp.mason-lspconfig")(manager)
require("plugins.lsp.nvim-lspconfig")(manager)
require("plugins.lsp.renamer")(manager)
require("plugins.lualine")(manager)
require("plugins.lualine-lsp-status")(manager)
require("plugins.markdown-preview")(manager)
require("plugins.mkdir")(manager)
require("plugins.noice")(manager)
require("plugins.numb")(manager)
require("plugins.nvim-autopairs")(manager)
require("plugins.nvim-ghost")(manager)
require("plugins.nvim-notify")(manager)
require("plugins.nvim-spectre")(manager)
require("plugins.nvim-surround")(manager)
require("plugins.nvim-syntax-info")(manager)
require("plugins.nvim-treesitter")(manager)
require("plugins.nvim-treesitter-context")(manager)
require("plugins.nvim-treesitter-textobjects")(manager)
require("plugins.nvim-treesitter-textsubjects")(manager)
require("plugins.nvim-ts-autotag")(manager)
require("plugins.nvim-various-textobjs")(manager)
require("plugins.nvim_context_vt")(manager)
require("plugins.oil")(manager)
require("plugins.oil-git-signs")(manager)
require("plugins.oklch-color-picker")(manager)
require("plugins.overseer")(manager)
require("plugins.pantran")(manager)
require("plugins.react-extract")(manager)
require("plugins.registers")(manager)
require("plugins.render-markdown")(manager)
require("plugins.satellite")(manager)
require("plugins.skkeleton")(manager)
require("plugins.smear-cursor")(manager)
require("plugins.sort")(manager)
require("plugins.tabset")(manager)
require("plugins.tiny-inline-diagnostic")(manager)
require("plugins.toggleterm")(manager)
require("plugins.tokyonight")(manager)
require("plugins.treesj")(manager)
require("plugins.trouble")(manager)
require("plugins.undotree")(manager)
require("plugins.vim-better-whitespace")(manager)
require("plugins.vim-illuminate")(manager)
require("plugins.vimdoc-ja")(manager)
require("plugins.visual-whitespace")(manager)
require("plugins.which-key")(manager)
require("plugins.wtf")(manager)
manager.unlock()

vim.api.nvim_create_user_command("PluginList", function()
    local buf = vim.api.nvim_create_buf(false, true)
    local ids = {}

    for name, _ in pairs(manager.plugins or {}) do
        table.insert(ids, name)
    end

    if #ids == 0 then
        ids = { "No plugins found" }
    else
        table.sort(ids)
    end

    vim.api.nvim_buf_set_lines(buf, 0, -1, false, ids)
    vim.api.nvim_set_current_buf(buf)
end, {})
