local manager = require("utils.manager")

manager.lock()
require("plugins.2048")
require("plugins.Comment")
require("plugins.blamer")
require("plugins.bufferline")
require("plugins.capture")
require("plugins.ccc")
require("plugins.cmdline-hl")
require("plugins.dashboard")
require("plugins.ddc.ddc")
require("plugins.ddc.ddc-file")
require("plugins.ddc.ddc-filter-matcher_head")
require("plugins.ddc.ddc-filter-sorter_rank")
require("plugins.ddc.ddc-path")
require("plugins.ddc.ddc-source-buffer")
require("plugins.ddc.ddc-source-file")
require("plugins.ddc.ddc-source-lsp")
require("plugins.ddc.ddc-ui-native")
require("plugins.ddu.ddu")
require("plugins.ddu.ddu-filter-converter_devicon")
require("plugins.ddu.ddu-filter-matcher_substring")
require("plugins.ddu.ddu-kind-file")
require("plugins.ddu.ddu-source-buffer")
require("plugins.ddu.ddu-source-file_rec")
require("plugins.ddu.ddu-source-line_dir")
require("plugins.ddu.ddu-source-lsp")
require("plugins.ddu.ddu-ui-ff")
require("plugins.denippet")
require("plugins.deps.denops")
require("plugins.deps.nui")
require("plugins.deps.nvim-web-devicons")
require("plugins.deps.plenary")
require("plugins.dropbar")
require("plugins.fidget")
require("plugins.friendly-snippets")
require("plugins.gitsigns")
require("plugins.history-ignore")
require("plugins.hlargs")
require("plugins.hlchunk")
require("plugins.hop")
require("plugins.indent-blankline")
require("plugins.lazygit")
require("plugins.lsp.lazydev")
require("plugins.lsp.mason")
require("plugins.lsp.mason-lspconfig")
require("plugins.lsp.nvim-lspconfig")
require("plugins.lsp.renamer")
require("plugins.lualine")
require("plugins.lualine-lsp-status")
require("plugins.markdown-preview")
require("plugins.mkdir")
require("plugins.noice")
require("plugins.numb")
require("plugins.nvim-autopairs")
require("plugins.nvim-clorizer")
require("plugins.nvim-ghost")
require("plugins.nvim-notify")
require("plugins.nvim-spectre")
require("plugins.nvim-syntax-info")
require("plugins.nvim-treesitter")
require("plugins.nvim-treesitter-context")
require("plugins.nvim-ts-autotag")
require("plugins.nvim_context_vt")
require("plugins.oil")
require("plugins.oil-git-signs")
require("plugins.pantran")
require("plugins.registers")
require("plugins.render-markdown")
require("plugins.satellite")
require("plugins.skkeleton")
require("plugins.smear-cursor")
require("plugins.tabset")
require("plugins.toggleterm")
require("plugins.tokyonight")
require("plugins.treesj")
require("plugins.undotree")
require("plugins.vim-better-whitespace")
require("plugins.vimdoc-ja")
require("plugins.which-key")
require("plugins.wtf")
manager.unlock()

vim.api.nvim_create_user_command("PluginList", function()
    local buf = vim.api.nvim_create_buf(false, true)
    local ids = {}

    for name, _ in pairs(manager.plugins or {}) do
        table.insert(ids, name)
    end

    if #ids == 0 then
        ids = { "No plugins found" }
    else
        table.sort(ids)
    end

    vim.api.nvim_buf_set_lines(buf, 0, -1, false, ids)
    vim.api.nvim_set_current_buf(buf)
end, {})
