local wezterm = require 'wezterm'
local act = wezterm.action

return {
    keys = {
        -- custom
        { key = '/',          mods = 'CTRL',       action = wezterm.action.SendString('\x1f') },
        { key = 'T',          mods = 'CTRL|SHIFT', action = wezterm.action.Multiple { { SendKey = { key = 'a', mods = 'CTRL' } }, { SendKey = { key = 'c' } } } },
        { key = 'Tab',        mods = 'CTRL',       action = wezterm.action.Multiple { { SendKey = { key = 'a', mods = 'CTRL' } }, { SendKey = { key = 'n' } } } },

        { key = 'Tab',        mods = 'CTRL|SHIFT', action = wezterm.action.Multiple { { SendKey = { key = 'a', mods = 'CTRL' } }, { SendKey = { key = 'p' } } } },

        { key = 'W',          mods = 'CTRL|SHIFT', action = wezterm.action.Multiple { { SendKey = { key = 'a', mods = 'CTRL' } }, { SendKey = { key = '&' } } } },
        -- standard
        { key = 'Enter',      mods = 'ALT',        action = act.ToggleFullScreen },
        { key = ')',          mods = 'CTRL',       action = act.ResetFontSize },
        { key = ')',          mods = 'SHIFT|CTRL', action = act.ResetFontSize },
        { key = '+',          mods = 'CTRL',       action = act.IncreaseFontSize },
        { key = '+',          mods = 'SHIFT|CTRL', action = act.IncreaseFontSize },
        { key = '-',          mods = 'CTRL',       action = act.DecreaseFontSize },
        { key = '-',          mods = 'SHIFT|CTRL', action = act.DecreaseFontSize },
        { key = '-',          mods = 'SUPER',      action = act.DecreaseFontSize },
        { key = '0',          mods = 'CTRL',       action = act.ResetFontSize },
        { key = '0',          mods = 'SHIFT|CTRL', action = act.ResetFontSize },
        { key = '0',          mods = 'SUPER',      action = act.ResetFontSize },
        { key = '=',          mods = 'CTRL',       action = act.IncreaseFontSize },
        { key = '=',          mods = 'SHIFT|CTRL', action = act.IncreaseFontSize },
        { key = '=',          mods = 'SUPER',      action = act.IncreaseFontSize },
        { key = 'C',          mods = 'CTRL',       action = act.CopyTo 'Clipboard' },
        { key = 'C',          mods = 'SHIFT|CTRL', action = act.CopyTo 'Clipboard' },
        { key = 'F',          mods = 'CTRL',       action = act.Search 'CurrentSelectionOrEmptyString' },
        { key = 'F',          mods = 'SHIFT|CTRL', action = act.Search 'CurrentSelectionOrEmptyString' },
        { key = 'K',          mods = 'CTRL',       action = act.ClearScrollback 'ScrollbackOnly' },
        { key = 'K',          mods = 'SHIFT|CTRL', action = act.ClearScrollback 'ScrollbackOnly' },
        { key = 'L',          mods = 'CTRL',       action = act.ShowDebugOverlay },
        { key = 'L',          mods = 'SHIFT|CTRL', action = act.ShowDebugOverlay },
        { key = 'M',          mods = 'CTRL',       action = act.Hide },
        { key = 'M',          mods = 'SHIFT|CTRL', action = act.Hide },
        { key = 'P',          mods = 'CTRL',       action = act.ActivateCommandPalette },
        { key = 'P',          mods = 'SHIFT|CTRL', action = act.ActivateCommandPalette },
        { key = 'R',          mods = 'CTRL',       action = act.ReloadConfiguration },
        { key = 'R',          mods = 'SHIFT|CTRL', action = act.ReloadConfiguration },
        { key = 'U',          mods = 'CTRL',       action = act.CharSelect { copy_on_select = true, copy_to = 'ClipboardAndPrimarySelection' } },
        { key = 'U',          mods = 'SHIFT|CTRL', action = act.CharSelect { copy_on_select = true, copy_to = 'ClipboardAndPrimarySelection' } },
        { key = 'V',          mods = 'CTRL',       action = act.PasteFrom 'Clipboard' },
        { key = 'V',          mods = 'SHIFT|CTRL', action = act.PasteFrom 'Clipboard' },
        { key = 'Z',          mods = 'CTRL',       action = act.TogglePaneZoomState },
        { key = 'Z',          mods = 'SHIFT|CTRL', action = act.TogglePaneZoomState },
        { key = '_',          mods = 'CTRL',       action = act.DecreaseFontSize },
        { key = '_',          mods = 'SHIFT|CTRL', action = act.DecreaseFontSize },
        { key = 'c',          mods = 'SHIFT|CTRL', action = act.CopyTo 'Clipboard' },
        { key = 'c',          mods = 'SUPER',      action = act.CopyTo 'Clipboard' },
        { key = 'f',          mods = 'SHIFT|CTRL', action = act.Search 'CurrentSelectionOrEmptyString' },
        { key = 'f',          mods = 'SUPER',      action = act.Search 'CurrentSelectionOrEmptyString' },
        { key = 'k',          mods = 'SHIFT|CTRL', action = act.ClearScrollback 'ScrollbackOnly' },
        { key = 'k',          mods = 'SUPER',      action = act.ClearScrollback 'ScrollbackOnly' },
        { key = 'l',          mods = 'SHIFT|CTRL', action = act.ShowDebugOverlay },
        { key = 'm',          mods = 'SHIFT|CTRL', action = act.Hide },
        { key = 'm',          mods = 'SUPER',      action = act.Hide },
        { key = 'n',          mods = 'SHIFT|CTRL', action = act.SpawnWindow },
        { key = 'n',          mods = 'SUPER',      action = act.SpawnWindow },
        { key = 'p',          mods = 'SHIFT|CTRL', action = act.ActivateCommandPalette },
        { key = 'r',          mods = 'SHIFT|CTRL', action = act.ReloadConfiguration },
        { key = 'r',          mods = 'SUPER',      action = act.ReloadConfiguration },
        { key = 't',          mods = 'SUPER',      action = act.SpawnTab 'CurrentPaneDomain' },
        { key = 'u',          mods = 'SHIFT|CTRL', action = act.CharSelect { copy_on_select = true, copy_to = 'ClipboardAndPrimarySelection' } },
        { key = 'v',          mods = 'SHIFT|CTRL', action = act.PasteFrom 'Clipboard' },
        { key = 'v',          mods = 'SUPER',      action = act.PasteFrom 'Clipboard' },
        { key = 'z',          mods = 'SHIFT|CTRL', action = act.TogglePaneZoomState },
        { key = 'phys:Space', mods = 'SHIFT|CTRL', action = act.QuickSelect },
        { key = 'PageUp',     mods = 'SHIFT',      action = act.ScrollByPage(-1) },
        { key = 'PageDown',   mods = 'SHIFT',      action = act.ScrollByPage(1) },
        { key = 'Insert',     mods = 'SHIFT',      action = act.PasteFrom 'PrimarySelection' },
        { key = 'Insert',     mods = 'CTRL',       action = act.CopyTo 'PrimarySelection' },
        { key = 'Copy',       mods = 'NONE',       action = act.CopyTo 'Clipboard' },
        { key = 'Paste',      mods = 'NONE',       action = act.PasteFrom 'Clipboard' },
    },

    key_tables = {
        search_mode = {
            { key = 'Enter',     mods = 'NONE', action = act.CopyMode 'PriorMatch' },
            { key = 'Escape',    mods = 'NONE', action = act.CopyMode 'Close' },
            { key = 'n',         mods = 'CTRL', action = act.CopyMode 'NextMatch' },
            { key = 'p',         mods = 'CTRL', action = act.CopyMode 'PriorMatch' },
            { key = 'r',         mods = 'CTRL', action = act.CopyMode 'CycleMatchType' },
            { key = 'u',         mods = 'CTRL', action = act.CopyMode 'ClearPattern' },
            { key = 'PageUp',    mods = 'NONE', action = act.CopyMode 'PriorMatchPage' },
            { key = 'PageDown',  mods = 'NONE', action = act.CopyMode 'NextMatchPage' },
            { key = 'UpArrow',   mods = 'NONE', action = act.CopyMode 'PriorMatch' },
            { key = 'DownArrow', mods = 'NONE', action = act.CopyMode 'NextMatch' },
        },

    }
}
