name: Test init.sh

on:
  workflow_dispatch:
    inputs:
      action:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v1
      - name: executing test
        run: curl -sSf https://raw.githubusercontent.com/shizukani-cp/dotfiles/main/install.sh | bash

